project_name: Lockstep
copyright_holder_full: Tencent
copyright_holder_short: Tencent
input_file: components.xlsx
output_file: ATTRIBUTIONS.txt
license_config: licenses.yaml
template_config: templates.yaml
license_serial_starts:
  MIT: 1
  BSD-3-Clause: 1
component_spacing: 1
show_source_url: true  # Global setting to control whether to show source code URLs   